### ISSUE TITLE
Roadmap to configurability

### ISSUE THREAD

**Issue by acao** [techworkersco/chrono-map-template#1]
## Baseline
- [ ] clone airtable schema from discontent mods
- [ ] simple & advanced customization docs
- [ ] create tags/tag type tables, fields
- [ ] custom label for "action" i.e. "event"
- [ ] customize texts with airtable

## Nice to have
- [ ] describe additional field types with configuration mapped to airtable
- [ ] i18n/l8n
- [ ] alternative backends - graphql (strapi, graphcms, baserow), airtable, faunadb, static git/s3 files
